function [Result, MBDF, Message, CalculatedValue] = ANNCalculator(TrainingData, TestingData, CalculatorData)
    

    regressionANN = fitrnet(...
                            TrainingData(:, 1:end-1), ...
                            TrainingData(:,end), ...
                            'LayerSizes', [15, 15] , ...
                            'Activations', 'Relu', ...
                            'Lambda', 0, ...
                            'IterationLimit', 1000, ...
                            'Standardize', true);

    partitionedModel = crossval(regressionANN, 'KFold', 5);
    validationPredictions = kfoldPredict(partitionedModel);
    yfit = regressionANN.predict(table2array(TestingData(:, 1:end-1)));
    

    % ---------------------------------------------------------------------
    % Calculated Value Pre-processing
    if ~isrow(CalculatorData)
        CalculatorData = CalculatorData';
    end
    CalculatedValue = regressionANN.predict(CalculatorData);
    
    Result.TrainedData = validationPredictions;
    Result.TestedData = yfit;
    Result.AccuracyTrain = accuracyAnalysis(table2array(TrainingData(:, end)), validationPredictions);
    Result.AccuracyTest  = accuracyAnalysis(table2array(TestingData(:, end)), yfit);
    pause(0.5);

    R2Train = Result.AccuracyTrain(6);
    R2Test  = Result.AccuracyTest(6);
    MAPETrain = Result.AccuracyTrain(10);
    MAPETest  = Result.AccuracyTest(10);

    [MBDF, ~] = MBDFCalculator(table2array(TrainingData(:, end)), ...
                                table2array(TestingData(:, end)), ...
                                validationPredictions, ...
                                yfit);
    Message = sprintf(['Train Process\n' ...
                          'R2 %.1f, MAPE %.1f%%\n' ...
                          '-----------------------\n' ...
                          'Test Process\n' ...
                          'R2 %.1f, MAPE %.1f%%\n' ...
                          '-----------------------\n' ...
                          'MBDF: %.2f'], R2Train,   ...
                                                    MAPETrain, ...
                                                    R2Test,    ...
                                                    MAPETest,  ...
                                                    MBDF);
end