function [Results, MBDF, Message, CalculatedValue] = GPRCalculator(TrainingData, TestingData, CalculatorData)
    

    phi = [mean(std(table2array(TrainingData(:,1:end-1))));1;std(table2array(TrainingData(:, end)))/sqrt(2)];
    Sigma = 1e-2 * std(table2array(TrainingData(:, end))) + 2 * 1e-3 * std(table2array(TrainingData(:, end)));

    regressionGP = fitrgp(...
                        TrainingData(:,1:end-1), ...
                        TrainingData(:, end), ...
                        'BasisFunction', 'constant', ...
                        'KernelFunction', 'rationalquadratic', ...
                        'KernelParameters', phi, ...
                        'Sigma', Sigma, ...
                        'Standardize', true);

    partitionedModel = crossval(regressionGP, 'KFold', 5);
    validationPredictions = kfoldPredict(partitionedModel);
    yfit = regressionGP.predict(TestingData(:, 1: end-1));

    % ---------------------------------------------------------------------
    % Calculated Value Pre-processing
    if ~isrow(CalculatorData)
        CalculatorData = CalculatorData';
    end
    CalculatedValue = regressionGP.predict(CalculatorData);


    Results.TrainedData = validationPredictions;
    Results.TestedData = yfit;
    Results.AccuracyTrain = accuracyAnalysis(table2array(TrainingData(:, end)), validationPredictions);
    Results.AccuracyTest  = accuracyAnalysis(table2array(TestingData(:, end)), yfit);
    pause(0.5);

    R2Train = Results.AccuracyTrain(6);
    R2Test  = Results.AccuracyTest(6);
    MAPETrain = Results.AccuracyTrain(10);
    MAPETest  = Results.AccuracyTest(10);

    [MBDF, ~] = MBDFCalculator(table2array(TrainingData(:, end)), ...
                                table2array(TestingData(:, end)), ...
                                validationPredictions, ...
                                yfit);
    Message = sprintf(['Train Process\n' ...
                          'R2 %.1f, MAPE %.1f%%\n' ...
                          '-----------------------\n' ...
                          'Test Process\n' ...
                          'R2 %.1f, MAPE %.1f%%\n' ...
                          '-----------------------\n' ...
                          'MBDF: %.2f'], R2Train,   ...
                                                    MAPETrain, ...
                                                    R2Test,    ...
                                                    MAPETest,  ...
                                                    MBDF);
end