function [Results, MBDF, Message] = SVR(TrainingData, TestingData)
    
    Epsilon = iqr(table2array(TrainingData(:,end)))/13.49;
    BC = iqr(table2array(TrainingData(:,end)))/1.349;
    regressionSVM = fitrsvm(...
                            TrainingData(:,1:end-1), ...
                            TrainingData(:, end), ...
                            'KernelFunction', 'polynomial', ...
                            'PolynomialOrder', 3, ...
                            'KernelScale', 'auto', ...
                            'BoxConstraint', BC, ...
                            'Epsilon', Epsilon, ...
                            'Standardize', true);

    partitionedModel = crossval(regressionSVM, 'KFold', 5);
    validationPredictions = kfoldPredict(partitionedModel);
    yfit = regressionSVM.predict(table2array(TestingData(:, 1: end-1)));

    
    Results.TrainedData = validationPredictions;
    Results.TestedData  = yfit;
    Results.AccuracyTrain = accuracyAnalysis(table2array(TrainingData(:, end)), validationPredictions);
    Results.AccuracyTest  = accuracyAnalysis(table2array(TestingData(:, end)), yfit);
    pause(0.5);
    
    R2Train = Results.AccuracyTrain(6);
    R2Test  = Results.AccuracyTest(6);
    MAPETrain = Results.AccuracyTrain(10);
    MAPETest  = Results.AccuracyTest(10);


    [MBDF, ~] = MBDFCalculator(table2array(TrainingData(:, end)), ...
                                table2array(TestingData(:, end)), ...
                                validationPredictions, ...
                                yfit);
    Message = sprintf(['Train Process\n' ...
                          'R2 %.1f, MAPE %.1f%%\n' ...
                          '-----------------------\n' ...
                          'Test Process\n' ...
                          'R2 %.1f, MAPE %.1f%%\n' ...
                          '-----------------------\n' ...
                          'MBDF: %.2f'], R2Train,   ...
                                                    MAPETrain, ...
                                                    R2Test,    ...
                                                    MAPETest,  ...
                                                    MBDF);

end